export const FACULTIES = [
  "Faculty of Applied & Computer Science",
  "Faculty of Management Science",
  "Faculty of Engineering & Technology",
  "Faculty of Human Science",
];

export const PROGRAMMES_BY_FACULTY = {
  "Faculty of Applied & Computer Science": [
    "Analytical Chemistry",
    "Agricultural Management",
    "Information Technology",
    "Non-Destructive Testing",
    "Biotechnology",
    "Environmental Science",
    "Extended Information Technology",
    "Medical Laboratory Science",
  ],
  "Faculty of Management Science": [
    "Financial Information Systems",
    "Cost & Management Accounting",
    "Internal Auditing",
    "Human Resource Management",
    "Logistics & Supply Chain Management",
    "Marketing",
    "Retail Business Management",
    "Sport Management",
  ],
  "Faculty of Engineering & Technology": [
    "Chemical Engineering",
    "Civil Engineering",
    "Industrial Engineering",
    "Mechanical Engineering",
    "Metallurgical Engineering",
    "Electronic Engineering",
    "Power Engineering",
    "Process Control Engineering",
    "Computer Systems Engineering",
    "Operations Management",
    "Electrical Engineering",
  ],
  "Faculty of Human Science": [
    "Fashion",
    "Photography",
    "Graphic Design & Fine Art",
    "Food Service Management",
    "Tourism Management",
    "Public Relations",
    "Ecotourism Management",
    "Legal Assistance",
    "Labour Law",
    "Safety Management",
    "Policing",
    "B Ed (Senior Phase & FET Teaching)",
    "Communication Studies",
  ],
};
